import type { Metadata } from "next";
import "@newjersey/stencil-react-export/packages/stencil-library/dist/stencil-library/css/styles.css";
import Script from "next/script";
import DefineCustomElementsLoader from "@/components/DefineCustomElementsLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <DefineCustomElementsLoader />
      <body>{children}</body>
    </html>
  );
}
